### ISSUE TITLE
Integrate hs_auth

### ISSUE THREAD

**Issue by seanjparker** [unicsmcr/hs_application#12]
We need to integrate hs_applications and hs_auth

This would allow us to to the following:

- [x] Restirct routes to users with specific auth levels

- [x] Invitations for teams and applicants #3 

- [ ] Change their applications before they have been reviewed

- [ ] Add application review system #7

**Comment by kzalys** [comment]
For the integration with `hs-auth` I'd recommend something like this:
1. if the user's `Authorization` header is empty, redirect them to `hs_auth/login` with the return URL in the header `Referer`. This will ask the user to login and redirect them to the return URL with a valid JWT in `Authorization`
2. whenever the user makes a request with a token in `Authorization` send a GET to `hs_auth/api/v1/users/verify` with the token in `Authorization`. If the token is valid it will return a 200, otherwise it will return a 401.
3. if you need any information about the user, send a GET to `hs_auth/api/v1/users/me` with the JWT in `Authorization`. This will return a 200 and the user object if the token is valid or a 401 and no user if it's not.

Things to note:
- `hs_auth/login` is not implemented yet so you could just implement a temporary solution by sending some placeholder email and password as a POST to `hs_auth/api/v1/login`
- it would great if you used `hs_auth/api/v1/users/verify` over `hs_auth/api/v1/users/me` whereever possible as the verify endpoint does not make a query to the DB and is much faster. I will extend the verify endpoint to include the user's auth level in the response to make it more useful.
- you can see examples on using the `hs_auth` API here: https://www.getpostman.com/collections/5130023edeb6bcc83fcf (import it to Postman)

**Comment by seanjparker** [comment]
> For the integration with `hs-auth` I'd recommend something like this:
> 
> 1. if the user's `Authorization` header is empty, redirect them to `hs_auth/login` with the return URL in the header `Referer`. This will ask the user to login and redirect them to the return URL with a valid JWT in `Authorization`
> 2. whenever the user makes a request with a token in `Authorization` send a GET to `hs_auth/api/v1/users/verify` with the token in `Authorization`. If the token is valid it will return a 200, otherwise it will return a 401.
> 3. if you need any information about the user, send a GET to `hs_auth/api/v1/users/me` with the JWT in `Authorization`. This will return a 200 and the user object if the token is valid or a 401 and no user if it's not.
> 
> Things to note:
> 
> * `hs_auth/login` is not implemented yet so you could just implement a temporary solution by sending some placeholder email and password as a POST to `hs_auth/api/v1/login`
> * it would great if you used `hs_auth/api/v1/users/verify` over `hs_auth/api/v1/users/me` whereever possible as the verify endpoint does not make a query to the DB and is much faster. I will extend the verify endpoint to include the user's auth level in the response to make it more useful.
> * you can see examples on using the `hs_auth` API here: https://www.getpostman.com/collections/5130023edeb6bcc83fcf (import it to Postman)

Is the first bullet point in "things to note" still true? @kzalys

**Comment by kzalys** [comment]
> > For the integration with `hs-auth` I'd recommend something like this:
> > 
> > 1. if the user's `Authorization` header is empty, redirect them to `hs_auth/login` with the return URL in the header `Referer`. This will ask the user to login and redirect them to the return URL with a valid JWT in `Authorization`
> > 2. whenever the user makes a request with a token in `Authorization` send a GET to `hs_auth/api/v1/users/verify` with the token in `Authorization`. If the token is valid it will return a 200, otherwise it will return a 401.
> > 3. if you need any information about the user, send a GET to `hs_auth/api/v1/users/me` with the JWT in `Authorization`. This will return a 200 and the user object if the token is valid or a 401 and no user if it's not.
> > 
> > Things to note:
> > 
> > * `hs_auth/login` is not implemented yet so you could just implement a temporary solution by sending some placeholder email and password as a POST to `hs_auth/api/v1/login`
> > * it would great if you used `hs_auth/api/v1/users/verify` over `hs_auth/api/v1/users/me` whereever possible as the verify endpoint does not make a query to the DB and is much faster. I will extend the verify endpoint to include the user's auth level in the response to make it more useful.
> > * you can see examples on using the `hs_auth` API here: https://www.getpostman.com/collections/5130023edeb6bcc83fcf (import it to Postman)
> 
> Is the first bullet point in "things to note" still true? @kzalys

Yes I'm still working on it

**Comment by kzalys** [comment]
@seanjparker The `hs_auth` login page is now implemented on branch `login-frontend`

**Comment by seanjparker** [comment]
Closed in favour of #25
